# Generated by Django 5.0.6 on 2024-06-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_content_remove_blog_head_blog_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='head',
            new_name='headings',
        ),
    ]
