# Generated by Django 5.0.6 on 2024-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_content_blog_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='headings',
        ),
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.AddField(
            model_name='blog',
            name='contents',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Heading',
        ),
        migrations.AddField(
            model_name='blog',
            name='headings',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
