# Generated by Django 5.0.6 on 2024-06-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_contents_remove_blog_headings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='blog_images'),
            preserve_default=False,
        ),
    ]
