# Generated by Django 5.0.6 on 2024-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=models.TextField(max_length=10000),
        ),
    ]
