# Generated by Django 5.0.6 on 2024-06-12 07:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contents',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
