# Generated by Django 5.0.6 on 2024-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_contents_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
