# Generated by Django 5.0.6 on 2024-06-14 07:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=120)),
                ('like', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('headings', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='blog_images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
