# Generated by Django 5.0.6 on 2024-06-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBlog',
        ),
    ]
